alias bp='. ~/.bashrc'

alias b='cd ../'
alias bb='cd ../../'
alias bbb='cd ../../../'
alias bbbb='cd ../../../../'
alias bbbbb='cd ../../../../../'

alias cdw='cd ~/workspace'

alias gp='git pull'
alias gs='git status'
alias gd='git diff'

alias ls='ls -hF --color=auto'
alias l='ls -lF'
alias ll='ls -alF'
alias lt='ls -ltrF'
alias ll='ls -alF'
alias lls='ls -alSrF'
alias llt='ls -altrF'
