#!/bin/bash

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Copy the configuration files.
echo "Copying .bash_aliases"
cp $SCRIPT_DIR/bash/bash_aliases ~/.bash_aliases

echo "Copying .bashrc"
cp $SCRIPT_DIR/bash/bashrc ~/.bashrc
