#
# Colorful Terminal
#
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad

#
# Aliases
#
source ~/.bash_aliases

#
# Android
#
export ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/r21
export ANDROID_NDK_ROOT=/usr/local/Cellar/android-ndk/r8
PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

#
# Cocos2d-X
#
export NDK_ROOT=$ANDROID_NDK_ROOT
export COCOS2DX_HOME=~/workspace/cocos2d-x
# core dump for Android cocos2d-x project
alias ndkdump='adb logcat | $NDK_ROOT/ndk-stack -sym obj/local/armeabi/'

#
# Git
#
# NOTE: brew install git bash-completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

#
# Go Lang
#
export GOPATH=~/workspace/go
PATH=$GOPATH/bin:$PATH

#
# mark/jump
# (http://jeroenjanssens.com/2013/08/16/quickly-navigate-your-filesystem-from-the-command-line.html)
#
export MARKPATH=$HOME/.marks
function jump {
  cd -P $MARKPATH/$1 2>/dev/null || echo "No such mark: $1"
}
function mark {
  mkdir -p $MARKPATH; ln -s $(pwd) $MARKPATH/$1
}
function unmark {
  rm -i $MARKPATH/$1
}
function marks {
  ls -l $MARKPATH | sed 's/  / /g' | cut -d' ' -f9- | sed 's/ -/\t-/g' && echo
}


#
# Node.js
#
export NODE_PATH=/usr/local/lib/node_modules:~/node_modules
PATH=~/node_modules/.bin:$PATH

#
# PHP
#
PATH=/Applications/XAMPP/xamppfiles/bin:$PATH

#
# Python
#
export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

#
# Ruby
#
# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

