#
# Colorful Terminal
#
export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export PS1="\[\033[40m\]\[\033[33m\][ \u@\H:\[\033[32m\]\w\[\033[33m\]\$(__git_ps1 \" \[\033[35m\]{\[\033[36m\]%s\[\033[35m\]}\")\[\033[33m\] ]$\[\033[0m\] "

#
# Aliases
#
source ~/.bash_aliases

#
# Android
#
export ANDROID_SDK_ROOT=/usr/local/Cellar/android-sdk/r21
export ANDROID_NDK_ROOT=/usr/local/Cellar/android-ndk/r8
PATH=$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/platform-tools:$PATH

#
# Boot2Docker
#
$(boot2docker shellinit)

#
# Cocos2d-X
#
export NDK_ROOT=$ANDROID_NDK_ROOT
export COCOS2DX_HOME=~/workspace/cocos2d-x
# core dump for Android cocos2d-x project
alias ndkdump='adb logcat | $NDK_ROOT/ndk-stack -sym obj/local/armeabi/'

#
# Git
#
# NOTE: brew install git bash-completion
if [ -f `brew --prefix`/etc/bash_completion ]; then
  . `brew --prefix`/etc/bash_completion
fi

export GIT_PS1_SHOWDIRTYSTATE="1"
. $HOME/workspace/configs/MacOSX/git-prompt.sh
PATH=$HOME/workspace/configs/git/bin:$PATH

#
# Go Lang
#
export GOPATH=~/workspace/go
PATH=$GOPATH/bin:$PATH

#
# Haskell
#
PATH=~/.cabal/bin:$PATH

#
# Java
#
export JAVA_HOME=`/usr/libexec/java_home -v 1.8`

#
# Node.js
#
export NODE_PATH=/usr/local/lib/node_modules:~/node_modules
PATH=~/node_modules/.bin:$PATH

#
# PHP
#
PATH=/Applications/XAMPP/xamppfiles/bin:$PATH

#
# Python
#
# pip should only run if there is a virtualenv currently activated
export PIP_REQUIRE_VIRTUALENV=true
# cache pip-installed packages to avoid re-downloading
export PIP_DOWNLOAD_CACHE=$HOME/.pip/cache
syspip() {
  PIP_REQUIRE_VIRTUALENV="" pip "$@"
}
export PYTHONPATH="/usr/local/lib/python2.7/site-packages:$PYTHONPATH"

#
# RabbitMQ
#
# NOTE: brew install rabbitmq
PATH=$PATH:/usr/local/sbin

#
# Ruby
#
# This loads RVM into a shell session.
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

#
# Z
#
# NOTE: brew install z
if [ -f `brew --prefix`/etc/profile.d/z.sh ]; then
  . `brew --prefix`/etc/profile.d/z.sh
fi

#
# Autoenv
#
# NOTE: brew install autoenv
# NOTE: The following has to be placed at the end of bash_profile.
# It seems to have conflict with another above (?).
source /usr/local/opt/autoenv/activate.sh

