alias bp='. ~/.bash_profile'

alias b='cd ../'
alias bb='cd ../../'
alias bbb='cd ../../../'
alias bbbb='cd ../../../../'
alias bbbbb='cd ../../../../../'

alias cdw='cd ~/workspace'

alias dr='docker run -d --env-file=$HOME/.docker-registry --name registry -p 5000:5000 google/docker-registry'

alias gp='git pull'
alias gs='git status'
alias gd='git diff'

# Julia was not available on brew yet as of writing this so installed it with
# dmg.
alias julia='/Applications/Julia.app/Contents/Resources/julia/bin/julia'

alias ls='ls -hFG'
alias l='ls -lF'
alias ll='ls -alF'
alias lt='ls -ltrF'
alias ll='ls -alF'
alias lls='ls -alSrF'
alias llt='ls -altrF'

# Make sure you have done this:
# ln -s /Applications/Sublime\ Text.app/Contents/SharedSupport/bin/subl /usr/local/bin/subl
alias s='subl'

