# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
source ~/.zsh_aliases

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(gem git rails ruby rvm)

source $ZSH/oh-my-zsh.sh

# Customize to your needs...
# Essential paths
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games

# LightDM is the default X display manager for Ubuntu 11.10.
PATH=/usr/lib/lightdm/lightdm:$PATH

# Custom scripts in $HOME/bin directory.
PATH=$HOME/bin:$PATH

# Haskell cabal
PATH=$HOME/.cabal/bin:$PATH

# Android ndk
PATH=$HOME/workspace/android-ndk-r7:$HOME/workspace/android-ndk-r7/toolchains/arm-linux-androideabi-4.4.3/prebuilt/linux-x86/bin:$PATH

# Android sdk
PATH=$HOME/workspace/android-sdk-linux_x86/tools:$HOME/workspace/android-sdk-linux_x86/platform-tools:$PATH

# Play framework
PATH=$HOME/workspace/play:$PATH

# Node.js
export NODE_PATH=/usr/local/lib/node_modules:$HOME/node_modules
PATH=~/node_modules/.bin:$PATH

# RVM
PATH=$HOME/.rvm/bin:$PATH

# Load RVM into a shell session *as a function*
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"

# For Emacs Tramp mode to work
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ '

